apiVersion: v1
kind: Service
metadata:
  name: tasks-service
spec:
  selector:
    app: tasks
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8000 # 외부에서 접속할 수 있는 port 번호
      targetPort: 8000 # 컨테이너 내부의, Pod 내부의 포트
