apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: hgj0619/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default" # coreDns 사용하기 serviceName.namespace
              # value: "10.103.15.33"
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
